### ISSUE TITLE
做的很好，希望可以加入自定义Ollama API的地址

### ISSUE THREAD

**Issue by mciart** [CaicoLeung/bob-plugin-ollama-translator#2]
如题，这样就不止有本地模式了

**Comment by CaicoLeung** [comment]
感谢提Issue，已支持自定义API URL.

**Comment by CaicoLeung** [comment]
@mciart 我没测试，这个api返回内容需要是兼容OpenAI结构体的。
有什么问题请反馈

**Comment by mciart** [comment]
> @mciart 我没测试，这个api返回内容需要是兼容OpenAI结构体的。 有什么问题请反馈
当我设置为类似：
http://4.home.mc***.com:11434/api/generate时
其中4.home.mc***.com是家中IPv4 DDNS的域名
通过其他客户端可以正常调用
会一直等待，没有返回结果，我是小白不是很懂
![photo_2024-08-14 16 49 15](https://github.com/user-attachments/assets/b1cdf5a7-fb66-434c-9864-14c35d1552df)

**Comment by mciart** [comment]
![Uploading Xnip2024-08-14_16-55-46.png…]()

**Comment by CaicoLeung** [comment]
你把/api/generate改为/v1/chat/completions应该就好了

**Comment by mciart** [comment]
我试试

**Comment by mciart** [comment]
也是不行

**Comment by CaicoLeung** [comment]
@mciart  更新了一个版本。你下载最新版再试试？

**Comment by mciart** [comment]
![photo_2024-08-14 17 24 00](https://github.com/user-attachments/assets/c950f2c9-1bf5-4450-afcf-8eb729d418b8)

**Comment by mciart** [comment]
插件未返回有效结果，会不会是流式传输造成的

**Comment by CaicoLeung** [comment]
@mciart 不是/api/v1/chat/completions，前面不需要/api

**Comment by mciart** [comment]
可以了，谢谢🙏。哈哈哈

**Comment by mciart** [comment]
可以了，谢谢🙏。哈哈哈
