### ISSUE TITLE
自定义 prompt 不生效

### ISSUE THREAD

**Issue by youngboyooo** [CaicoLeung/bob-plugin-ollama-translator#4]
我试了中英文，都无法生效

**Comment by CaicoLeung** [comment]
是处于翻译模式吗？目前只对翻译模式下有效

**Comment by FreyaOne** [comment]
确实，我也遇到这个问题，我使用的是deepseek，使用自定义prompt模式，输入`collaborate`，这个单词，输出的答案如下：
### 1. 词源  
**Collaborate** 源自拉丁语 *collaborare*，由 *com-*（意为“一起”）和 *laborare*（意为“工作”）组合而成，字面意思是“共同劳动”。17世纪通过法语 *collaborer* 进入英语，最初用于宗教语境（如“与敌对势力合作”），后逐渐演变为中性或积极的“协作”含义。

---

### 2. 发音  
- **英式发音**：/kəˈlæb.ə.reɪt/  
  - 重音在第二音节（`lab`），元音弱化（ə）常见于非重读音节。  
- **美式发音**：/kəˈlæb.ə.reɪt/ 或 /koʊˈlæb.ə.reɪt/  
  - 部分方言可能将第一个音节读作 /koʊ/（类似“co-”）。  

---

### 3. 定义  
- **主要含义**：为共同目标而与他人或团体合作，尤指创造性或专业性的工作。  
  - 例：*Scientists collaborated on the research project.*  
- **次要含义**（历史/贬义）：与敌人或占领者合作，含背叛意味。  
  - 例：*During the war, some citizens were accused of collaborating with the enemy.*  

---

### 4. 用法  
- **学术/工作场景**：  
  - *The two universities collaborated to develop a new vaccine.*  
- **艺术创作**：  
  - *The director collaborated with a famous composer on the film’s soundtrack.*  
- **负面语境**：  
  - *The regime forced artists to collaborate with propaganda efforts.*  

---

### 5. 同义词与反义词  
- **同义词**：  
  - **Cooperate**：更强调自愿配合，目标不一定相同（例：*The witness cooperated with police.*）。  
  - **Team up**：非正式，常用于短期合作（例：*They teamed up for the competition.*）。  
- **反义词**：  
  - **Work alone**：独立工作。  
  - **Sabotage**：故意破坏合作。  

---

### 6. 相关词汇  
- **Collaboration**（名词）：合作行为或成果。  
  - 例：*Their collaboration won an award.*  
- **Collaborator**（名词）：合作者；贬义指“通敌者”。  
  - 例：*She was a key collaborator on the project.*（中性）  
  - *Wartime collaborators were punished.*（贬义）  

---

### 7. 文化/历史背景  
- **二战时期**，“collaborator”在欧洲被广泛用于指责与纳粹合作的人，导致该词一度带有强烈负面色彩。  
- **现代用法**：因全球化与跨学科项目增多，“collaborate”在商业、科技、艺术领域成为高频词，强调平等共创（如 *collaborative tools* 指在线协作软件）。  

--- 

如需进一步探讨某一方面，可随时补充提问！

我的Bob设置是这样的

<img width="452" height="756" alt="Image" src="https://github.com/user-attachments/assets/3c5704ee-7e3e-4006-add3-5cf67a9bbc7f" />

prompt内容为：

你是一个英语语言学家，用户会提供一个英语单词，请你完成以下内容：
1. 判断这个词属于哪种词性（名词/动词/形容词/副词）；并给出详细的单词解释，和相应的例句帮助我记忆；
2. 列出该词的其他常见词形变化（如动词形式、名词形式、形容词形式、副词形式），如果没有就说明；
3. 对每个词形给出简短定义（中英对照）；
4. 为原始词和派生词各举一个英语例句，附中文翻译；
5. 输出结构整洁、适合快速学习。
6. 请用简体中文回答。

输出的内容虽然也是翻译，但似乎不是我的prompt控制的🤔
